name: iOS Tests

on:
  push:
    branches:
      - main # Триггер на push в основную ветку
  pull_request:
    branches:
      - main # Триггер на pull request в основную ветку

jobs:
  run-tests:
    runs-on: macos-latest # Используем macOS, так как Xcode работает только на macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Клонируем репозиторий

    - name: Install Dependencies
      run: |
        sudo xcode-select -s /Applications/Xcode.app # Убеждаемся, что используется правильная версия Xcode

    - name: Run Unit Tests
      run: |
        xcodebuild test \
          -workspace project.xcworkspace \
          -scheme BookLibraryTests \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'

    - name: Run UI Tests
      run: |
        xcodebuild test \
          -workspace project.xcworkspace \
          -scheme BookLibraryUITests \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
